### ISSUE TITLE
Use .config instead of .meta for this

### ISSUE THREAD

**Issue by joshka** [bigskysoftware/dotmeta#4]
While probably a bikeshed consideration, .config is a much more obvious name to use for this.

HN thread with many agreements:
- https://news.ycombinator.com/item?id=36472613

Previous project suggesting .config:
- https://dot-config.github.io/

I'd suggest leaving this issue around and collecting thumbs up / down (Please don't comment with +1s on this, unless you have something novel to add).

**Comment by ghost** [comment]
I would agree with this. the Go programming language uses `.config` on Unix:

https://godocs.io/os#UserConfigDir

based on this spec:

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by emidevops** [comment]
**~/.config** as defined in basedir spec is for user configurations.

A non ambiguous name could be **.project** but it conflicts with Eclipse file.

Eclipse also use **.settings** folder, maybe it's a good compromise?

**Comment by RGBCube** [comment]
Why not just `config/` or `project/`? These files are a part of the project, and shouldn't really be ignored.

**Comment by joshka** [comment]
>I would agree with this. the Go programming language uses .config on Unix:

> ~/.config as defined in basedir spec is for user configurations.

`~/.config` is different to `.config` within your project. The XDG spec does not extend to relative paths, so the only real overlap between this and the XDG folder will occur if you happen to put a git repo in a path like your home directory (in which case, it maps quite nicely)

> A non ambiguous name could be .project but it conflicts with Eclipse file.

> Eclipse also use .settings folder, maybe it's a good compromise?

Neither are good options if they are already used by a reasonably popular tool as this **will** cause conflicts

> Why not just config/ or project/? These files are a part of the project, and shouldn't really be ignored.

There is a reasonable subset of developers that do think these files are noise compared to the main structure of their project (I'm on the fence myself as it's nice to be able to just see what a project uses right in the project root on a github landing page). A general (unwritten) conventions in many software projects is that the software stack often owns the files and folders without dots, while files with dots are owned by additional tools, using `config/` or `project/` would be worse than `.meta/` in that regard.

**Comment by Frizlab** [comment]
Hello!

Why was this closed? In particular what is the resolution? My preference goes to `.config` as well as most people in this thread apparently, but the site is still `dotmeta.org` and still advocates for `.meta`, what did I miss?

Thanks!

**Comment by joshka** [comment]
> Hello!
> 
> Why was this closed? In particular what is the resolution? My preference goes to `.config` as well as most people in this thread apparently, but the site is still `dotmeta.org` and still advocates for `.meta`, what did I miss?
> 
> Thanks!

Just closing out a bunch of old issues I raised that have no next steps. No response from the repo owner on this, so it doesn't really serve any purpose other than to be shouting in the wind.
