### ISSUE TITLE
These are dotfiles, use `dotfiles/` or `.dotfiles/`

### ISSUE THREAD

**Issue by offsetcyan** [bigskysoftware/dotmeta#5]
The directory should be `dotfiles/` or `.dotfiles/` because it's normal, it's what the files are (they are dotfiles), and everyone knows or should know what dotfiles are. There is precedent for this, see GNU stow and everyone's home directory life hacks (i.e git for managing dotfiles). It's also not the name of a big tech company. It's also not the name of an XDG base directory (i.e. `.config/`, `.local/`).

**Comment by strager** [comment]
I thought dotmeta was for config files.

**Comment by offsetcyan** [comment]
Since, I've made a website on the subject https://dotfiles-matter.click/
